import earphones from "../../src/assets/images/earphones.png"
import iPhone from "../../src/assets/images/iphone14promax.jpg"
import iPhone1 from "../../src/assets/images/iphone-leather-walle.png"
import iPhone11pro from "../../src/assets/images/11 pro.jpg"
import iPhone11 from "../../src/assets/images/11.jpg"

import ipad from "../../src/assets/images/ipad_mini.png"
import iMac1 from "../../src/assets/images/iphone14promax.jpg"


export const useInformation = () => {
    const categories = [
        {
            name: 'watch',
            img: iMac1,
            categories: 'clock',
            id: 1
        },
        {
            name: 'AirPods',
            img: earphones,
            categories: 'earphones',
            id: 2
        },
        {
            name: 'iPhone',
            img: iPhone,
            categories: 'iPhone',
            id: 3
        },
        {
            name: 'ipad',
            img: ipad,
            categories: 'ipad',
            id: 4
        },
        {
            name: 'MacBook',
            img: iPhone1,
            categories: 'MacBook',
            id: 5
        },
        {
            name: 'iMac',
            img: ipad,
            categories: 'iMac',
            id: 6
        },
    ]
    const products = [
        {
            name: "Iphone 11",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            img: iPhone11,
            replacingMainCamera:'3 900 ₽',
            replacingBattery:'6 500 ₽',
            categories: 'iPhone',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            id: 8,
            bodyReplacement :'от 16000 ₽',

        },
        {
            name: "Iphone 11 Pro",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            img: iPhone11pro,
            replacingMainCamera:'3 900 ₽',
            replacingBattery:'6 500 ₽',
            categories: 'iPhone',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            id: 7,
            bodyReplacement :'от 16000 ₽',

        },
        {
            name: "Iphone 11 Pro Max",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            img: iPhone11,
            replacingMainCamera:'3 900 ₽',
            replacingBattery:'6 500 ₽',
            categories: 'iPhone',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            id: 1,
            bodyReplacement :'от 16000 ₽',

        },

        {
            name: "Iphone",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            img: iPhone1,
            replacingMainCamera:'3 900 ₽',
            replacingBattery:'6 500 ₽',
            categories: 'iPhone',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            id: 2,
            bodyReplacement :'от 16000 ₽',

        },
        {
            name: "Iphone",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: iPhone, categories: 'iPhone',
            id: 3
        },
        {
            name: "Iphone",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            img: iPhone,
            categories: 'iPhone',
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            id: 4
        },
        {
            name: "Iphone",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: iPhone,
            categories: 'iPhone',
            id: 5},
        {
            name: "Iphone",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: earphones, categories: 'iPhone',
            id: 6
        },
        {
            name: "Clock",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: earphones,
            categories: 'clock',
            id: 7
        },
        {
            name: "Clock",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: earphones,
            categories: 'clock',
            id: 8
        },
        {
            name: "Clock",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: earphones,
            categories: 'clock',
            id: 9
        },
        {
            name: "Clock",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            img: earphones,
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            touchScreenIf:'14 900 ₽',
            categories: 'clock',
            id: 10

        },
        {
            name: "AirPods",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: earphones,
            categories: 'earphones',
            id: 11
        },
        {
            name: "AirPods",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: earphones,
            categories: 'earphones',
            id: 11
        },
        {
            name: "AirPods",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: earphones,
            categories: 'earphones',
            id: 11
        },
        {
            name: "AirPods",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: earphones,
            categories: 'earphones',
            id: 12
        },
        {
            name: "AirPods",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: earphones,
            categories: 'earphones',
            id: 13
        },
        {
            name: "AirPods",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: earphones,
            categories: 'earphones',
            id: 14
        },
        {
            name: "MacBook",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: ipad,
            categories: 'MacBook',
            id: 15
        },
        {
            name: "MacBook",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: ipad,
            categories: 'MacBook',
            id: 16},
        {
            name: "MacBook",
            diagnostics: 'бесплатно',
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: ipad, categories: 'MacBook',
            DataRecovery:"4 500 ₽",
            id: 17
        },
        {
            name: "MacBook",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: ipad,
            categories: 'MacBook',
            id: 18
        },
        {
            name: "iMac",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            img: iMac1,
            categories: 'iMac',
            id: 19
        },
        {
            name: "iMac",
            DataRecovery:"4 500 ₽",
            diagnostics: 'бесплатно',
            dataTransfer:'от 500 ₽',
            img: iMac1,
            polishingScreen:'от 5000 ₽',
            categories: 'iMac',
            id: 20,
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',
            bodyReplacement :'от 16000 ₽',

            faceIDRepair:'10 500 ₽',

        },
        {

            name: "iMac",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            img: iMac1,
            categories: 'iMac',
            touchScreenIf:'14 900 ₽',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            replacingBattery:'6 500 ₽',
            batteryError:'5200 ₽',
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',
            speakerMesh:'от 2500 ₽',

            bodyReplacement :'от 16000 ₽',
            id: 21,
            faceIDRepair:'10 500 ₽',
            polishingScreen:'от 5000 ₽',
            touchScreen :'12 490 ₽',


        },
        {
            name: "iMac",
            diagnostics: 'бесплатно',
            DataRecovery:"4 500 ₽",
            dataTransfer:'от 500 ₽',
            img: iMac1,
            touchScreen :'12 490 ₽',
            touchScreenIf:'14 900 ₽',
            categories: 'iMac',
            replacementDisplay:'18 900 ₽',
            replacementDisplayOriginal:'22 100 ₽',
            faceIDRepair:'10 500 ₽',
            resolvingError:'4 500 ₽',
            displayModule:'10 490 ₽',
            polishingScreen:'от 5000 ₽',
            id: 22,
            replacingMainCamera:'3 900 ₽',
            replacingMainRearCamera:'6 900 ₽',

            batteryError:'5200 ₽',
            replacingBattery:'6 500 ₽',

        },


    ]
    const aboutWork  = [
        {job:'Диагностика',id:1},
        {job:'Восстановление данных (телефон перезагружается на "яблоке"',id:2},
        {job:'Перенос данных',id:3},
        {job:'Ремонт Face ID',id:4},
        {job:'Полировка экрана от царапин',id:5},
        {job:'Замена сенсорного стекла (стекло экрана)\n' +
                '\n',id:6},
        {job:'Замена сенсорного стекла + тачскрин (если сильно разбит или не работает сенсор)\n' +
                '\n',id:7},
        {job:'Замена дисплея (экрана), Original переклеенный\n' +
                '\n',id:8},
        {job:'Замена дисплея (экрана), Original переклеенный\n' +
                '\n',id:9},
        {job:'Замена дисплея (экрана), Original снятый\n' +
                '\n',id:10},
        {job:'Замена дисплея (экрана), Original снятый\n' +
                '\n',id:11},
        {job:'Устранение ошибки дисплея (проверка подлинности экрана)\n' +
                '\n',id:12},
        {job:'Замена дисплея (экрана), Original снятый' +
                '',id:13},
        {job:'Замена дисплейного модуля (TFT High Copy) копия высокого качества\n'
                ,id:14},
        {job:'Замена дисплейного модуля (OLED High Copy) копия высокого качества\n' +
                '\n' ,id:15},
        {job:'Замена аккумуляторной батареи\n' +
                '\n',id:16},
        {job:'Устранение ошибки АКБ (проверка подлинности аккумуляторной батареи)',id:17},
        {job:'Замена линзы основной камеры (стекло камеры)\n' +
                '\n',id:18},
        {job:'Замена основной (задней) камеры\n' +
                '\n',id:19},
        {job:'Замена сетки динамика\n' +
                '\n',id:20},
        {job:'Замена корпуса (только снятый оригинал)\n' +
                '\n',id:21},


    ]
    return {categories,products ,aboutWork}
}